### ISSUE TITLE
Not Able To Scroll Down and View Contact Details in Landscape Mode

### ISSUE THREAD

**Issue by neupanedipen** [midhunhk/random-contact#10]
#### Expected behavior
On viewing a random contact we should be able to view the full details in Landscape mode as in Potrait view and should be able to scroll down to view the full details.<br>

#### Actual behavior
But on rotating the screen the contact details are not shown and you can&apos;t even scroll down to see the full details of contact.<br>

#### How to reproduce
1. Download Random Contact from [Play Store ](https://play.google.com/store/apps/details?id=com.ae.apps.randomcontact)and Launch it.<br>
2. View a conatct details in potrait mode.<br>
3. Switch the orientation of your screen to landscape mode and rotate your screen to view the contact details in Landscape mode.<br>
You won&apos;t be able to scroll down and view the full contact details in landscape view.<br>
* Operating system: Android 6.0.1<br>
* Device: Samsung Galaxy J5<br>
* App Version: 3.0.1<br>

#### Recording Of The Bug
Here's a video recording of not being able to scroll down on a contact details in landscape mode.<br>
 <iframe width="560" height="315" src="https://www.youtube.com/embed/x0Dt6ygt19o" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@neupanedipen/not-able-to-scroll-down-and-view-contact-details-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by midhunhk** [comment]
Thank you @neupanedipen for reporting this, I will take a look at this issue and provide a fix with the next release - 3.1.0 (telephone)
