### ISSUE TITLE
Add ability to edit contact groups after creation

### ISSUE THREAD

**Issue by megantaylor** [midhunhk/random-contact#24]
### Actual behaviour
I can create a contact group and add contacts to it but after this is done I can't edit the contact group to add/remove contacts.

### Expected behaviour
I should be able to edit a contact group I have created to add/remove contacts.

**Comment by midhunhk** [comment]
Thank you for creating this issue. This will be taken care as part of #21  and #22 .
However I will keep this ticket open until it is resolved.

**Comment by midhunhk** [comment]
This change is implemented with the latest rewrite. Version 4.0 of the app is now available on the Google Play Store. 
Please note that you would have to recreate the contact groups as the app database has been upgraded.
